### ISSUE TITLE
Code needs to be modular. 

### ISSUE THREAD

**Issue by didlie** [open-easyrtc/open-easyrtc#10]
There is alot of great code here, but it is so intertwined and could use a much simpler peer object and peer handling object. I don't think the peer objects in easyrtc can be networked economically into a p2p  mesh network, serverless.

**Comment by hthetiot** [comment]
@didlie ok, sorry but you create too much noise, you need to read the fucking manual and code and if you want to contribute make PR, this is not a forum and there is no plan to change the API only maintain it.

I do not use this library myself I only maintain it for existing users.
