### ISSUE TITLE
[feature request] support for kurento media server?

### ISSUE THREAD

**Issue by IRGC** [open-easyrtc/open-easyrtc#12]
can we have support for kurento media server for one to many video,audio stream broadcast within single room?
https://github.com/Kurento/kurento-media-server

**Comment by chrisdepas** [comment]
Isn't one of the design goals of Kurento is that it is complete?

I.e. The [docs](https://doc-kurento.readthedocs.io/en/6.11.0/user/about.html#kurento-design-principles) say this:

> Developers do not need to be aware of internal Kurento Media Server complexities: all the applications can deployed in any technology or framework the developer likes, from client to server. From browsers to cloud services.

In any case, it supports javascript at the moment, so I don't see why you would go to the trouble of modifying EasyRTC to talk to existing Kurento applications, when you could just use Kurento instead. Is there a particular reason why you need EasyRTC and Kurento to talk?

There are a limited number of people contributing at the moment, and the [Kurento API](https://streamoriented.docs.apiary.io/#introduction/editors) seems to be complex (unlike easyrtc, which has really simple communication), so I think it's not very likely that this will happen anytime soon unfortunately.

Additionally, I think this would probably be out of the scope of this repo, as I understand it EasyRTC is basically a shortcut to having a functional cross-browser WebRTC application. This would probably be better suited to a new `open-easyrtc-kurento` repo / npm registry package

**Comment by hthetiot** [comment]
That as nothing to do with EasyRTC itself.
If you know how to use EasyRTC you can send and intercept SDP and send it to any MCU/SFU.

**Comment by IRGC** [comment]
@chrisdepas @hthetiot i like easyrtc because it is very easy to use and the room function, if `open-easyrtc` support kurento then i can/others too use it easily , may be i am the voice of many other nOOb developers who is trying to build one to many broadcasting using webrtc technology.
