### ISSUE TITLE
ES modules + rollup

### ISSUE THREAD

**Issue by qutran** [open-easyrtc/open-easyrtc#14]
First of all thank you for the forking this library and making it alive.
I want to propose to refactor the code step-by-step for using with es-modules (https://caniuse.com/#feat=es6-module) and the rollup that has first-class es-modules support.
From my side I want to propose my active support as a contributor for this features. Just share your thoughts about it.

**Comment by hthetiot** [comment]
I personally don't like or need es module, UMD works great and is cross platform and cross compiler (require.js, Typescript, AMD, ES module) I and as a mater or fact once compiled to es5 es module will do the same.

Owever, if you do a PR I will consider it depending the quality of the improvements it is providing, finally make sure to look at actual grunt build as you may think easyrtc.js is the actual implementation where in fact it's easyrtc_int.js
