### ISSUE TITLE
Default STUN options are invalid

### ISSUE THREAD

**Issue by kakaroto** [open-easyrtc/open-easyrtc#15]
The default stun options from `lib/easyrtc_default_options.js` have : 
```js
option.appIceServers = [                                    // Array of STUN and TURN servers. By default there is only publicly available STUN servers.
    {urls: "stun:stun.l.google.com:19302"},
    {urls: "stun:stun.sipgate.net"},
    {urls: "stun:217.10.68.152"},
    {urls: "stun:stun.sipgate.net:10000"},
    {urls: "stun:217.10.68.152:10000"}
];
```
Those are invalid because you use `urls` instead of `url` and since the code in `api/easyrtc.js` does this : 
```js
            item = iceConfig.iceServers[i];
            if( item.urls && item.urls.length ) {
               for( j = 0; j < item.urls.length; j++ ) {
                  processUrl(item.urls[j]);
               }
            }
            else if( item.url ) {
               processUrl(item.url);
            }
```
It will try to process each character as a url which will fail, so the `easyrtc._stunServers` end up being empty.

**Comment by hthetiot** [comment]
WebRTC adapter should add url from urls but i will fix this bug anyway. 
Thank you for report @kakaroto

**Comment by hthetiot** [comment]
Fixed by 3d96701c62819aa640b018c5204bdb6d1da60c8e will be released on 2.0.3

**Comment by hthetiot** [comment]
@kakaroto Quick notes.

Before the 3d96701 changes the urls were still added to `pc_config.iceServers`, webrtc adatper support `urls` as array or string and when string add then to `url` as string.

Meaning that the iceServers where in use by the PeerConnection in the end.
This does not mean the fixes was not needed but that it was not causing issues in term of stun use in the end by the PeerConnection.

```
js
            pc_config = {
                iceServers: iceConfig.iceServers
            };
```

```js
    /** @private */
    function processUrl(url) {
        var ipAddress;
        if (url.indexOf('turn:') === 0 || url.indexOf('turns:') === 0) {
            ipAddress = url.split(/[@:&]/g)[1];
            self._turnServers[ipAddress] = true;
        } else if (url.indexOf('stun:') === 0 || url.indexOf('stuns:') === 0) {
            ipAddress = url.split(/[@:&]/g)[1];
            self._stunServers[ipAddress] = true;
        }
    }

    /** @private */
    function processIceConfig(iceConfig) {

        var i, j, item;

        pc_config = {
            iceServers: []
        };

        self._turnServers = {};
        self._stunServers = {};

        if (
            !iceConfig ||
                !iceConfig.iceServers ||
                    typeof iceConfig.iceServers.length === "undefined"
        ) {
            self.showError(
                self.errCodes.DEVELOPER_ERR,
                "iceConfig received from server didn't have an array called iceServers, ignoring it"
            );
        } else {
            pc_config = {
                iceServers: iceConfig.iceServers
            };
        }

        for (i = 0; i < iceConfig.iceServers.length; i++) {
            item = iceConfig.iceServers[i];
            if( item.urls && item.urls.length ) {
               for( j = 0; j < item.urls.length; j++ ) {
                  processUrl(item.urls[j]);
               }
            }
            else if( item.url ) {
               processUrl(item.url);
            }
         }
    }
```

**Comment by hthetiot** [comment]
_turnServers and _stunServers end up only been used by getStats also.

**Comment by kakaroto** [comment]
Thanks for the fix! 
Yes, I did notice that the pc_config was being sent as is, and that the `_turnServers` and `_stunServers` were irrelevant but I didn't know that the webrtc spec itself accepted 'urls' as a string.
Regardless, it needed to be fixed and thanks for taking care of it so quickly :) I'm currently implementing webrtc support in a VTT application and found easyrtc to be very easy to work with. I'll report anything else I find while developing with it.
Thanks for your work! :)
