### ISSUE TITLE
Update urls and documentation

### ISSUE THREAD

**Issue by kakaroto** [open-easyrtc/open-easyrtc#16]
You have forked easyrtc into open-easyrtc (which is great as it would be a shame to let this library die off), but a lot of stuff still refers to easyrtc, such as the server example which suggets doing `require('easyrtc')` or the `updateCheckEnable` option which makes a version check on "http://easyrtc.com/version/?app=easyrtc" (which btw is a 404).
I'm sure there are other places that need fixing.

**Comment by hthetiot** [comment]
@kakaroto Yes we working on it. Good catch!

**Comment by hthetiot** [comment]
@kakaroto A lot of documentation have been fixed into #11  Thank to @chrisdepas

**Comment by hthetiot** [comment]
fixed by e3a235e38ff9a006ee7a2916a8af77084abae8e1

**Comment by hthetiot** [comment]
fixed by 4476ad817b803257f49440c556f2fcfb4c89befe

**Comment by hthetiot** [comment]
Closing for now @kakaroto Feel free to continue to report issues, I will try to take care of them.
