### ISSUE TITLE
Your browser doesn't appear to support WebRTC

### ISSUE THREAD

**Issue by gfreccia** [open-easyrtc/open-easyrtc#19]
Hi All,

I'm approaching to WebRTC.
I've installed the demo server, but when I try to connect to a demo app, with Firefox and Chrome, I've this error message:
_Your browser doesn't appear to support WebRTC._

I've Mint with Firefox 69 and Chrome 77.
I've another Mint installation working without errors.
What's the problem?

Thank you!

**Comment by hthetiot** [comment]
I cannot help you much, if one install work and a other does not.
Do you have a camera on both ?

**Comment by hthetiot** [comment]
Here is where the message come from:
- https://github.com/open-easyrtc/open-easyrtc/blob/7cb2ac275ce0ba893f3e7a9785b8f0d4b181b667/api/easyrtc_int.js#L2316

**Comment by kakaroto** [comment]
@gfreccia FYI: audio/video capture only works if you on https *or* using localhost. If you're trying the demo server on an address other than `localhost` and you haven't enabled SSL, then it won't work and will report that WebRTC isn't supported.
Note: actually, WebRTC is still supported, you could still connect and receive streams from others, you just can't capture from your own audio/video, so you wouldn't be able to send a stream to the others, but receiving would work fine, so the message is a slightly misleading.
