### ISSUE TITLE
Bad Ice Candidate When Not Connected to the Same Wifi

### ISSUE THREAD

**Issue by oividioscaeremos** [open-easyrtc/open-easyrtc#21]
I have deployed my app on heroku and it launches without a problem. And works perfectly when I use my computer and phone to do a call when they're both connected to the same wifi. But when I disconnect from wifi on my phone on turn on data, it suddenly gives the error;

```
doAnswerBody setRemoteDescription failed: InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Called in wrong state: kHaveLocalOffer
```

It doesn't work on demos either so I believe this is a problem with either easyrtc framework or the heroku itself. 

Note: This problem doesn't happen when the app is launched on localhost.

**Comment by hthetiot** [comment]
Do you have your own TURN server ?
- https://www.html5rocks.com/tutorials/webrtc/infrastructure/

**Comment by oividioscaeremos** [comment]
That was a big ouch for me. And means that I have still a lot to achieve... Since we have to care about the privacy, I have to install an opensource turn server on a server and work with it. There are a few open source turn server libraries around, but installation is something I haven't figured out yet. Do you by any chance have any guides that explains the steps I need to follow? I'm on the search.. Thank you for your answer.

**Comment by kakaroto** [comment]
I'm not sure if it's a connectivity issue.
I've seen that error happen when both sides try to call each other. You try to make a call to someone who has already initiated a call, it's a race condition which causes both calls to fail. I solved it by doing a call only if the remote's `easyrtcid.localeCompare(self_rtcid) > 1` 
The demos should have worked though so it could be a connection problem as well.

**Comment by oividioscaeremos** [comment]
As it turns out, if you're connected to the same wifi, firewall let's you do whatever you want to do. Since both the origin and the destination are known as secure. But when you try to call someone who is connected to a different network, there's this problem with firewalls. And it can be exceeded by using a TURN server instead of a STUN server. I'm currently using [xirsys's](https://www.xirsys.com) trial version, which gives you 500mb for development purposes. Not much but enough if you're not creating this app with a team.

**Comment by hthetiot** [comment]
WebRTC 101 you need TURN in the real world.

I recommend coturn (see docker image https://github.com/instrumentisto/coturn-docker-image).
