### ISSUE TITLE
clearMediaStream doesn't work in chrome

### ISSUE THREAD

**Issue by kakaroto** [open-easyrtc/open-easyrtc#22]
Hi, I found another bug!
 `clearMediaStream`  doesn't work in chrome (and by extension, so does setVideoObjectSrc with a `null` stream).
The problem is that `clearMediaStream` checks if the element has a `src` field defined and then clears it, but `setVideoObjectSrc` checks for a srcObject first (and on chrome, we can't create a URL from a stream and we use `srcObject` instead of `src`).
I think the simple fix is to replace the `if {} else if {} else if {};` with a `if {}; if {}; if {};`

**Comment by hthetiot** [comment]
This should fix the issue 866fa964b8a91fa8aa672a40f78829511052d732

**Comment by hthetiot** [comment]
released in 2.0.5
