### ISSUE TITLE
crash when trying to enumerate devices over http

### ISSUE THREAD

**Issue by kakaroto** [open-easyrtc/open-easyrtc#23]
`getSourceList` called by the `getVideoSourceList`, `getAudioSourceList` and `getAudioSinkList` calls `enumerateDevices` on `mediaDevices` without checking that `mediaDevices` exists. The `.catch()` is not helpful when there is no promise created. You should check for `navigator.mediaDevices && navigator.mediaDevices.enumerateDevices`  like you do with `supportsGetUserMedia`.

**Comment by hthetiot** [comment]
@kakaroto `supportsGetUserMedia` is made to check support for `getUserMedia` while `getSourceList` directly result in deviceList, I understand the issue. But what should be the `getSourceList` behavior in that case? call callback with empty results ? I think throw error is better in that case as it force the developer to handle the error. Tell me what you think.

**Comment by hthetiot** [comment]
@kakaroto would you prefer this, instead of throw error ?
```js
function getSourceList(callback, sourceType) {
        if (navigator.mediaDevices && navigator.mediaDevices.enumerateDevices) {
            navigator.mediaDevices.enumerateDevices().then(
                 function(values) {
                    var results = [];
                    for (var i = 0; i < values.length; i++) {
                        var source = values[i];
                        if (source.kind === sourceType) {

                            //backwards compatibility
                            if (!source.id) {
                                source.id = source.deviceId; 
                            }
                            
                            results.push(source);
                        }
                    }
                    callback(results);
                 }
              ).catch(
                function(reason) {
                   logDebug("Unable to enumerate devices (" + reason + ")");
                }
            );
        } else {
            logDebug("Unable to enumerate devices (navigator.mediaDevices not supported)");
        }
    }
```

**Comment by kakaroto** [comment]
Yes, that's exactly what I had intended, a check for enumerateDevices and a relevant message rather than a `cannot read property enumerateDevices of undefined` error. 

I hadn't realized that in case of a an error, the callback never gets called. I would suggest a `callback([])` be called in both error cases because that would indeed cause my app to get stuck. Or actually better, throw a new exception with the error message that gets logged so the application can handle it properly. Either solution would be fine for me, I don't know which you prefer for your library.

Thanks.

**Comment by hthetiot** [comment]
Will make PR soon @kakaroto
