### ISSUE TITLE
 FYI: audio/video capture only works if you on https *or* using localhost.

### ISSUE THREAD

**Issue by gfreccia** [open-easyrtc/open-easyrtc#24]
@gfreccia FYI: audio/video capture only works if you on https *or* using localhost. If you're trying the demo server on an address other than `localhost` and you haven't enabled SSL, then it won't work and will report that WebRTC isn't supported.
Note: actually, WebRTC is still supported, you could still connect and receive streams from others, you just can't capture from your own audio/video, so you wouldn't be able to send a stream to the others, but receiving would work fine, so the message is a slightly misleading.

_Originally posted by @kakaroto in https://github.com/open-easyrtc/open-easyrtc/issues/19#issuecomment-554706873_

**Comment by gfreccia** [comment]
Thanks for the answer!

But it's not completely clear for me what works and what doesn't work.
I've enabled SSL with _node server_ssl.js_ command.
Can I established audio connection between two browser on two different PC (no localhost)?
I've still the error messages when I try to accept the call!

**Comment by kakaroto** [comment]
Make sure your chrome/firefox version supports the API (it should if it's recent enough) https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Browser_compatibility

Also read the privacy and security section :
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security

The "WebRTC not supported" error is when getUserMedia is undefined which is what that last link explains.

**Comment by hthetiot** [comment]
Thank you @kakaroto 

@gfreccia This is normal behavior.

See: https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https

> getUserMedia allows you to listen in to the private conversations of the user. If it were enabled over unencrypted HTTP, this would allow an attacker to inject code that listens in and sends the conversations to the attacker. For example, if you if you are in a private conference room of a hotel with unencrypted WiFi, everybody in the vicinity of the hotel could listen in. Even if your app does not usually deal with sensitive conversations, an attacker could replace your code with theirs in order to listen in at a later time, when another app is in use.

> Therefore, getUserMedia is only available from secure contexts. For testing, you can exempt your domain by starting Chrome with --unsafely-treat-insecure-origin-as-secure="example.com", or simply test under http://localhost/.

> If you want your app to listen to the user's microphone, you must serve it via TLS. There is no way around it. If there were, it would be regarded as a security hole and fixed in the next version of the browsers.

> HINT

> You might have to add "http://" on the command line, e.g.: 
--unsafely-treat-insecure-origin-as-secure="http://example.com"
```

**Comment by hthetiot** [comment]
@gfreccia  I dont understand why you created another issue https://github.com/open-easyrtc/open-easyrtc/issues/19#issuecomment-554706873 was pretty clear.

Instead reply in your existing issue next time even if closed.

**Comment by hthetiot** [comment]
@gfreccia you will also need a TURN server for using WebRTC in the real world, based on your issues, I dont think you understand the full implication  of actualy using WebRTC fully.

https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_server_ice.md#easyrtc-server-ice-configuration
https://www.html5rocks.com/tutorials/webrtc/infrastructure/
