### ISSUE TITLE
iOS Devices

### ISSUE THREAD

**Issue by oividioscaeremos** [open-easyrtc/open-easyrtc#28]
Hey, I've been getting "Your browser doesn't support webrtc" error on chrome on ios devices. I've read stuff on internet about apple devices' not supporting webrtc, is it true? It can't be since I tried on a mac before and it worked without problem(safari) but whenever I try to use my application on iphone 6s, chrome says its not supported and safari only sends black screen. I'm not sure what I need to do on this point. Apple device support is fatal :/

I'm getting the error on iPhone 6S. How can I solve this?

**Comment by hthetiot** [comment]
EasyRTC work on safari on iOS properly alternatively you can use Cordova-plugin-iosrtc.

**Comment by hthetiot** [comment]
iOS chrome does not support webRTC but safari iOS does.

**Comment by hthetiot** [comment]
See:
- https://stackoverflow.com/questions/39790639/webrtc-support-on-chrome-browser-in-iphone-ipad

**Comment by oividioscaeremos** [comment]
Thank you hthetiot for your reply. It's unfortunate Apple is a huge black-box.

**Comment by hthetiot** [comment]
EasyRTC use feature detection of not supported it's because WebRTC API is not available that is that simple.

**Comment by hthetiot** [comment]
> Thank you hthetiot for your reply. It's unfortunate Apple is a huge black-box.

It's more google Chrome people that are lazy and don't implement WebRTC in the webview it's quite easy i even did it myself with Cordova-plugin-iosrtc see https://github.com/cordova-rtc/cordova-plugin-iosrtc

**Comment by oividioscaeremos** [comment]
Is it compatible with open-easyrtc or do I have to detect one's system and navigate to different pages? I'm pretty much all set-up with easyrtc so I don't really want to change all of my code right now.
