### ISSUE TITLE
Using open-easyrtc client in Electron with nodeIntegration=true

### ISSUE THREAD

**Issue by paddyesch** [open-easyrtc/open-easyrtc#32]
I'm evaluating the open-easyrtc client for use in Electron. When I set "nodeIntegration" to "false" in the BrowserWindow it works just like it would on a website (vanilla JS). However, I want to enable "nodeIntegration". With this I need to import the open-easyrtc client as Node.js module. The following steps were necessary.

(1) require("open-easyrtc"); does only import the server-side part, therefore is not needed.

(2) In the folder "node_modules" of your project copy the open-easyrtc folder and rename it to "easyrtc", open the index.js file and change the require to "./api/easyrtc".

(3) In "node_modules/easyrtc/api" open the easyrtc.js file and change "require('socket.io')" to "require('socket.io-client')" which was in line 5602. Otherwise the "io.connect" method will not exist. Also delete everything starting from line 11448 to 11917. Otherwise "easyrtc" is not available as module.

(4) In the folder "node_modules" copy the open-easyrtc folder and rename it to "easyrtc_lang", open the index.js file and change the require to "./api/easyrtc_lang".

(5) Tell easyrtc the serverName and serverPort to connect to with the method "easyrtc.setSocketUrl("http://localhost:12001");".

Would it be possible to provide these client node packages with npm? Maybe rename them to "open-easyrtc-client".

Thanks for your work on open-easyrtc!

**Comment by hthetiot** [comment]
@paddyesch Yes we can split the client, that can be a good idea.

**Comment by hthetiot** [comment]
We use Open-EasyRTC at Sylaps, none of the step you describe are required to make it work in Nodewebkit, that is similar to Electron (except Electron sucks ;)
