### ISSUE TITLE
easyrtc doesn't request permissions to capture video anymore

### ISSUE THREAD

**Issue by kakaroto** [open-easyrtc/open-easyrtc#38]
A consequence of this commit : 
https://github.com/open-easyrtc/open-easyrtc/commit/923081a2b78f4d0c599d2f8358c07bdd63c9255b

(even with the fixed typo from https://github.com/open-easyrtc/open-easyrtc/commit/220b8db723738bed5d163340f5d6f581c1c6eb4e)

My users have started complaining that it never asks for permissions to capture from the camera (audio doesn't seem affected by the change), tested on Chrome and Safari (Windows 10, iOS).
This also broke the feature of setting the deviceID to "default" to make it use the default camera, since it's not an exact id match anymore.

I assume it doesn't ask for permissions anymore because unless you have the exact id of the device, you can't request it to use it, and if you're not requesting the exact id, it won't ask for permission to use it. And without being given permissions, you can't know the id. So it's a chicken and egg problem.

I'll soon be using `easyrtc._presetMediaConstraints` to set min/max resolutions for capturing from the camera anyway, so it won't be a problem for me, but I thought you should know.

**Comment by hthetiot** [comment]
You want me to rollback @kakaroto ?

**Comment by hthetiot** [comment]
98b23d7886317dc5cf548231629810e46e38609e

**Comment by kakaroto** [comment]
Yep, thanks!
