### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by TriStarGod** [open-easyrtc/open-easyrtc#39]
Hi,
Just started playing with this software and loving it. I wanted to know if it supports

- Server-side recording
- Active speaker
- Transcription
- SIP integration

Also, I created server_spdyhtml2.js for server_example. Should I create a PR for that?

**Comment by TriStarGod** [comment]
The more I read about this open-easyrtc, the more I think this is not an SFU. I was looking for a combination TURN / SFU that runs on nodejs and can be easily hosted on heroku.

**Comment by kakaroto** [comment]
yeah, this only takes care of the signalling to setup the RTCPeerConnection, it doesn't include TURN or an SFU or anything like that.

**Comment by hthetiot** [comment]
@TriStarGod 
- Server-side recording: No
- Active speaker: Can be done with getStats
- Transcription: Can be done using tensorflow on MediaStream
- SIP integration: This is not EasyRTC role use https://jssip.net/ it's made for that.
- TURN: This is not EasyRTC role use CoTurn
- SFU:  This is not EasyRTC role use Korento, Jitsi, etc...

**Comment by TriStarGod** [comment]
@kakaroto @hthetiot Thanks for your input. I had my sample app working with Mediasoup and node-turn but I wanted to make it all work on Heroku (port issue). Hoped open-easyrtc would be a alternative but I guess not. Droplets, here I come.
Again, great project!

**Comment by hthetiot** [comment]
Mediasoup is great. EasyRTC can work with Mediasoup and any MCU it's just a matter of using server even to manipulate SDP

```js
easyrtc.events.on('emitEasyrtcCmd', function (connectionObj, msgType, msg, socketCallback, next) {
if (msgType === 'offer') {
// manipulate msg to send to MCU/SFU instead.
}
});
```
