### ISSUE TITLE
 Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

### ISSUE THREAD

**Issue by davexoyinbo** [open-easyrtc/open-easyrtc#40]
I keep getting 
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
at Easyrtc.createObjectURL (easyrtc.js:4152)
    at Easyrtc.setVideoObjectSrc (easyrtc.js:4618)
    at onUserMediaSuccess (easyrtc.js:4872)

**Comment by hthetiot** [comment]
How do you use setVideoObjectSrc exactly ?
Do you pass the MediaStream as a second argument ?

> easyrtc.setVideoObjectSrc( document.getElementById("myVideo"), easyrtc.getLocalStream());

Note: This working properly for me, it's most likely an issue on your usage of easyrtc.

**Comment by davexoyinbo** [comment]
It's now working. It was a setup issue
Thanks
