### ISSUE TITLE
How do I set metadata on each user or easyrtcid

### ISSUE THREAD

**Issue by davexoyinbo** [open-easyrtc/open-easyrtc#41]
How do I set metadata on each user or easyrtcid

**Comment by hthetiot** [comment]
See:
- https://github.com/open-easyrtc/open-easyrtc/blob/master/api/easyrtc_int.js#L1507
- https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_server_msgtypes.md#msgtype---setroomapifield

Example:
```js
easyrtc.setRoomApiField("trekkieRoom",  "favorite_alien", "Mr Spock");
easyrtc.setRoomOccupantListener( function(roomName, list){
	for( var i in list ){
		console.log("easyrtcid=" + i + " favorite alien is " + list[i].apiFields.favorite_alien);
	}
});

```
