### ISSUE TITLE
desktop capture plugin

### ISSUE THREAD

**Issue by crimson589** [open-easyrtc/open-easyrtc#42]
The demo for desktop capturing says a plugin is required to be installed in chrome in order to screen share, however the link to the plugin is dead.

I also can't find anything in the chrome web store for something called screen-capturing? is there a new link? or is this feature dead for now?

**Comment by nguereza-tony** [comment]
please try this link: [https://chrome.google.com/webstore/detail/screen-capturing/hccmdbhopgjapkajcmdegkpplnahngnl](https://chrome.google.com/webstore/detail/screen-capturing/hccmdbhopgjapkajcmdegkpplnahngnl)

**Comment by hthetiot** [comment]
You dont need plugin, you can simply use  navigator.mediaDevices.getDisplayMedia and easyrtc.register3rdPartyLocalMediaStream.

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia

Example:

```js
navigator.mediaDevices.getDisplayMedia({video: true}).then(function (stream) {
easyrtc.register3rdPartyLocalMediaStream(stream, 'screen:1');

// Then to add to existing connection
easyrtc.addStreamToCall(easyrtcId, 'screen:1', function (caller, streamName) {

});
})
```

**Comment by kylebakerio** [comment]
the demo should probably be updated, no?

**Comment by hthetiot** [comment]
@kylebakerio yes it should, We can also add easyrtc.getDisplayMedia for example.
