### ISSUE TITLE
How to enable echo cancellation?

### ISSUE THREAD

**Issue by kylebakerio** [open-easyrtc/open-easyrtc#47]
Mozilla tells me the process [looks like this](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints/audio):

```js
 navigator.mediaDevices.getUserMedia({
    audio: {
      sampleSize: 8,
      echoCancellation: true
    }
  })
```

But looking through source, I don't see that as an option anywhere, nor a way that it is exposed to add these options.

```js
// in self.getUserMediaConstraints...     
  if (!self.audioEnabled) {
            constraints.audio = false;
        }
        else {
            if (adapter && adapter.browserDetails && adapter.browserDetails.browser === "firefox") {
                constraints.audio = {};
                if (self._desiredAudioProperties.audioSrcId) {
                    constraints.audio.deviceId = self._desiredAudioProperties.audioSrcId;
                }
            }
            else { // chrome and opera
                constraints.audio = {mandatory: {}, optional: []};
                if (self._desiredAudioProperties.audioSrcId) {
                    constraints.audio.optional = constraints.audio.optional || [];
                    constraints.audio.optional.push({deviceId: self._desiredAudioProperties.audioSrcId});
                }
            }
        }
return constraints

// later...
        var mode = self.getUserMediaConstraints();
// later...
        navigator.getUserMedia(mode, onUserMediaSuccess, onUserMediaError);
```

I do see

```js
if (self._presetMediaConstraints) {
            constraints = self._presetMediaConstraints;
            delete self._presetMediaConstraints;
            return constraints;
        }
```

at the top of `getUserMediaConstraints`, but instead of enabling composing an option in, it will block execution of the rest of the function, which doesn't seem ideal...

How should I approach this within easyrtc?

**Comment by kakaroto** [comment]
You can probably just use this if you want custom constraints : 
```js
easyrtc._presetMediaConstraints = {
    audio: {
      sampleSize: 8,
      echoCancellation: true
    }
  }
```

**Comment by kylebakerio** [comment]
> You can probably just use this if you want custom constraints :
> 
> ```js
> easyrtc._presetMediaConstraints = {
>     audio: {
>       sampleSize: 8,
>       echoCancellation: true
>     }
>   }
> ```

Will that not prevent the rest of that function from running? Will that not be a problem? Do I then need to make sure I'm handling all the logic there myself (for per-browser specification, and later for video stuff if I add that)?

And where should I declare this--in the global scope right after declaring easyrtc I presume?

**Comment by kakaroto** [comment]
yes, you'd handle it yourself, you either use what the API provides or you build your own custom constraints, can't have it both ways. And you declare it where you would usually do the enableAudio/enableVideo, after easyrtc library is loaded of course.

**Comment by kylebakerio** [comment]
Sure, it would just be nice if instead of overwriting, I could compose in flags like this. It would be pretty easy to implement that way. As it's written, it's very tempting to just fork it, because otherwise I'll probably be copy/pasting the existing functionality and just adding my one little flag.

Would a pull request to modify this functionality be welcome?

**Comment by kylebakerio** [comment]
Looking through it more--what about having a 

`easyrtc.enableAEC([bool])` (audio echo cancellation) feature added?

**Comment by kakaroto** [comment]
Leaving that up to @hthetiot 
I'd personally like the enable audio/video to have an argument for extra parameters that get merged into the constraints object, so something like : 
```js
easyrtc.enableAudio(true, {echoCancellation: true})
```

**Comment by kylebakerio** [comment]
@kakaroto yeah, that's exactly what I mean by composition. That'd be ideal.

**Comment by kylebakerio** [comment]
Would a pull request for that be accepted, @hthetiot?

**Comment by hthetiot** [comment]
> Would a pull request for that be accepted, @hthetiot?

Sure @kylebakerio

**Comment by hthetiot** [comment]
```
navigator.mediaDevices.getUserMedia({
    audio: {
      sampleSize: 8,
      echoCancellation: true
    }
  }).then(function (stream) {
    easyrtc.register3rdPartyLocalMediaStream(stream, 'audio:1');

    // Then to add to existing connection
    easyrtc.addStreamToCall(easyrtcId, 'audio:1', function (caller, streamName) {

    });
});
```
