### ISSUE TITLE
Does EasyRTC API support for Python and Android?

### ISSUE THREAD

**Issue by linh-gist** [open-easyrtc/open-easyrtc#50]

**Comment by hthetiot** [comment]
Why not, its Websocket Signaling you can sockect to socket.io in many languages:
- https://python-socketio.readthedocs.io/en/latest/
- https://socket.io/blog/native-socket-io-and-android/

On android you can also use WebView, I have see people implementing EasyRTc protocol in Objective C# and even Swyft.
