### ISSUE TITLE
docker-compose.yml install error on npm install

### ISSUE THREAD

**Issue by garlofrank** [open-easyrtc/open-easyrtc#55]
Hi everyone.

I have tried to install the server example with docker compose and got an error

`npm notice`
`npm notice New minor version of npm available! 7.0.15 -> 7.1.2`
`npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.1.2>`
`npm notice Run `npm install -g npm@7.1.2` to update!`
`npm notice `
`npm ERR! code EISDIR`
`npm ERR! syscall copyfile`
`npm ERR! path /usr/local/lib/node_modules/npm`
`npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI`
`npm ERR! errno -21`
`npm ERR! EISDIR: illegal operation on a directory, copyfile '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'`

Thanks and Greetings

**Comment by garlofrank** [comment]
I have commented out the line for npm update in the Dockerfile and now I am getting another error.

`npm ERR! code 128`
`npm ERR! command failed`
`npm ERR! command git ls-remote ssh://git@github.com/priologic/easyrtc.git`
`npm ERR! Host key verification failed.`
`npm ERR! fatal: Could not read from remote repository.`
`npm ERR! `
`npm ERR! Please make sure you have the correct access rights`
`npm ERR! and the repository exists.`

**Comment by hthetiot** [comment]
should be fixed by https://github.com/open-easyrtc/open-easyrtc/commit/c1e3424c8a5de81ded6740b7a358c19cecb411ab#diff-33c410c95690d1f329c93ce7e9e6ad4e89ed63c114b3943faed7ddc42ad53147
