### ISSUE TITLE
Native Android and iOS Support

### ISSUE THREAD

**Issue by girijeshkumar2007** [open-easyrtc/open-easyrtc#62]
We want to use your library for some features in our mobile app both on Android and iOS.
The app is written in java and swift respectably.
I can't find any information if our team could help in this case?

**Comment by hthetiot** [comment]
@girijeshkumar2007 see https://github.com/cordova-rtc/cordova-plugin-iosrtc

Many have simply implemented easyrtc socket.io protocol and used native WebRTC also in java ans swift or objective-c.
