### ISSUE TITLE
How to use open-easyrtc in a Vuejs or Quasar project?

### ISSUE THREAD

**Issue by nilopaim** [open-easyrtc/open-easyrtc#63]
I've made a `npm install --save open-easyrtc` on my project.

On a Vuejs page I have 

`import easyrtc from "open-easyrtc";
export default {
  mounted() {
    var selfEasyrtcid = "";
    connect();
    function connect() {
      easyrtc.setVideoDims(640, 480);
      easyrtc.setRoomOccupantListener(convertListToButtons);
      easyrtc.setSocketUrl("//localhost:8443");
.
.
.`

And got the following error:

`open_easyrtc__WEBPACK_IMPORTED_MODULE_0___default.a.setVideoDims is not a function"`

What am I missing?

**Comment by hthetiot** [comment]
not sure, did you configure open-easyrtc as commonjs module ?

**Comment by nilopaim** [comment]
Not sure how to configure open-easyrtc inside a Quasar project. 

My first try was install using npm and import it on my pages, but everything did till now doesn't work. Probably I'm missing some basic point here.

If you can point me to the right direction I appreciate.

**Comment by hthetiot** [comment]
Example web pack config that works for me:

``` 
const path = require('path');
const webpack = require('webpack');

module.exports = {
    plugins: [
        new webpack.ProgressPlugin()
    ],
    entry: {
        ...
    },
    output: {
        ...
    },
    mode: 'production',
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'awesome-typescript-loader',
                exclude: /node_modules/
            }
        ]
    },
    resolve: {
        alias: {
            'open-easyrtc': path.resolve(__dirname, "node_modules/open-easyrtc/api/easyrtc.js"),
            'socket.io': path.resolve(__dirname, "node_modules/socket.io-client/dist/socket.io.slim.js"),
        },
        extensions: ['.tsx', '.ts', '.js']
    }
};

```

**Comment by nilopaim** [comment]
I will try this, sir.

Thanks a lot for your help, @hthetiot.
