### ISSUE TITLE
Doing Demos

### ISSUE THREAD

**Issue by didlie** [open-easyrtc/open-easyrtc#7]
So, I'm impressed. It works. Demos work. They do something. However, I am unable to locate any details of the WebRTC peer connection. I do not see the pc object, the SDP(local description) remoteDescription, ...nothing that looks like WebRTC. All I see is a socket connection. Please explain whats going on here. You are the genius of this working thing!

**Comment by hthetiot** [comment]
You did not search well enought please dont spam issues like that.
I replied by email to you.
See Client API here:
- https://github.com/open-easyrtc/open-easyrtc/blob/master/api/easyrtc_int.js
