### ISSUE TITLE
socket.io doesn't return Access-Control-Allow-Origin header when Origin header is sent so can't use EasyRTC across domains

### ISSUE THREAD

**Issue by benryves** [open-easyrtc/open-easyrtc#74]
I have a PHP application that I'd like to use EasyRTC with for real-time video chat. According to the [docs](https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_with_other_servers.md) this should be possible. I followed the instructions in the documentation, but when I try the `demo_audio_video_simple.html` demo on the PHP-based site I'm having CORS problems with requests to `/socket.io`:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://easyrtc.example.com/socket.io/?EIO=3&transport=polling&t=NrdrOhi. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

If I look at the headers that `/socket.io` is sending back in the Firefox developer console I can indeed see that it's missing the `Access-Control-Allow-Origin header`:

Request:

```
GET /socket.io/?EIO=3&transport=polling&t=NrdmVI9 HTTP/2
Host: easyrtc.example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: https://game.example.com
Connection: keep-alive
Referer: https://game.example.com/
Cookie: io=dRSRi4KXvEL_Kbv5AAAN
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
TE: trailers

```
Response:

```
HTTP/2 403 Forbidden
content-type: application/json
date: Sun, 28 Nov 2021 18:15:04 GMT
server: LiteSpeed
X-Firefox-Spdy: h2
```

However, if I copy and paste the URL being requested directly into the browser address bar, I do get a different set of headers back in response - including Access-Control-Allow-Origin:

Request:

```
GET /socket.io/?EIO=3&transport=polling&t=Nrdh9pB HTTP/2
Host: easyrtc.example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: io=vUC3lEXxioP0McRMAAAy
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```

Response:

```
HTTP/2 200 OK
content-type: text/plain; charset=UTF-8
access-control-allow-origin: *
set-cookie: io=vcL_-LefN1utSBaRAAAz; Path=/; HttpOnly; SameSite=Strict; secure
content-length: 103
date: Sun, 28 Nov 2021 18:44:31 GMT
server: LiteSpeed
X-Firefox-Spdy: h2
```

Unfortunately, I'm afraid I don't know my way around Node.js enough to figure out what exactly might be causing this. Running the demos directly from easyrtc.example.com works fine; this domain has been configured via cPanel's application manager to run `~/open-easyrtc-2.0.11/server_example/`.

I've noticed that if I edit the request and remove the Origin header and re-send it, the server responds with Access-Control-Allow-Origin. When running from the same domain the Origin header is not sent either, so the demo works.

I tried modifying `server_example/server_ssl.js` to include `io.set('origins', '*:*');` or `io.origins('*:*');` as some other sites have reported that this is required for CORS with Socket.IO prior to version 3 (and as far as I can see EasyRTC is using version 2.4.0) however this made no difference and the fact that the `Access-Control-Allow-Origin: *` header is sent when navigating to `/socket.io` via the browser's address bar makes me think that this sort of workaround would not be required.

Any guidance would be much appreciated, thank you!

**Comment by benryves** [comment]
After much inexpert fumbling I seem to have got something working. I'm not entirely sure where the issue is originating (Socket.IO, Node.JS, Phusion Passenger, LiteSpeed, cPanel...) so any clarification would be appreciated!

In my environment I need an `app.js`, previously I'd created this by duplicating `server.js` but I've now created a symlink instead (`ln -s server.js app.js`) which seems to be sufficient and means only one source file needs to be amended.

According to the Socket.IO 2.x documentation there is an `origins` configuration option that defaults to `'*'` and that should allow cross-origin requests to succeed. Attempting to explicitly change this to `'*'`, `'*:*'`, `'game.example.com'`, `'game.example.com:*'` and combinations thereof as both string literals or arrays of strings all failed for me - but they also stopped the demos from working on `easyrtc.example.com` too, with the API returning an explicit 403 error (with JSON payload) instead of the browser displaying a CORS error, so clearly it was having _some_ effect.

What does seem to have worked is to use the [`server.origins(fn)`](https://socket.io/docs/v2/server-api/#serveroriginsfn) function instead, which takes a function that can check the origin. Adding the following lines to `server.js` below the existing `// Start Socket.io` code gets this working across domains for me:

```
// Start Socket.io so it attaches itself to Express server
var socketServer = socketIo.listen(webServer, {"log level":1 });

// Cross-domain workaround presented below:
socketServer.origins((origin, callback) => {
    if (origin && ![
        'https://game.example.com',
        'https://easyrtc.example.com',
        '*'
    ].includes(origin)) {
        return callback('origin not allowed', false);
    }
    callback(null, true);
});
```

When running the demos across the same origin I found `origin` was not set (hence the initial check to see if it's present). The list of permitted domains that then follows also includes `'*'` as the Sockets.IO documentation claims:

> in some situations, when it is not possible to determine `origin` it may have value of `*`

This is probably the wrong way to fix this, but I am now at least able to place a video call from a page hosted on the main PHP-based website with EasyRTC hosted on a separate domain.

**Comment by hthetiot** [comment]
I will take a look when I have a moment, I have CORS working in production, but i think i have passed Socket.io parameters to use Websocket transport only to solve that.

**Comment by hthetiot** [comment]
```
// Cross-domain workaround presented below:
socketServer.origins((origin, callback) => {
    if (origin && ![
        'https://game.example.com',
        'https://easyrtc.example.com',
        '*'
    ].includes(origin)) {
        return callback('origin not allowed', false);
    }
    callback(null, true);
});
```

Your fix is valid, will add to sample server.

**Comment by hthetiot** [comment]
See https://github.com/open-easyrtc/open-easyrtc/commit/b78ccc5c68ceb7170069643a5129460ba6d19992#diff-5df089885a85c4b794c3f09be9ab04c105ff7bb08235ff07d7247cc59ec9d111

**Comment by benryves** [comment]
Brilliant, thank you very much for investigating and confirming the solution!

**Comment by hthetiot** [comment]
@benryves you did all the work :)
