### ISSUE TITLE
Comment regarding STUN server in README recommendation

### ISSUE THREAD

**Issue by didlie** [open-easyrtc/open-easyrtc#8]
I did allot of reading before I was able to answer the basic first questions about internals for this repo. STUN server is not internal: the implementer is expected to use the "most common application" [coturn](https://github.com/coturn/coturn)

**Comment by hthetiot** [comment]
RTFM 
- https://github.com/open-easyrtc/open-easyrtc/blob/5ea69776f319fab15a784f94db91a2c1f5154ef5/docs/easyrtc_server_ice.md#easyrtc-server-ice-configuration
