### ISSUE TITLE
eastrtc client API was removed as a doc, or it never existed?

### ISSUE THREAD

**Issue by didlie** [open-easyrtc/open-easyrtc#9]
Totally unable to find any existence of the doc file for the client API... only a reference to it in a file list. I looked for 5 minutes and didn't find it. Any road map?

**Comment by hthetiot** [comment]
Hey please stop that and look by yourself, you the first one in 3 years having this issue.
This is not a forum here:
- https://github.com/open-easyrtc/open-easyrtc/tree/master/docs/client_html_docs_lite
